spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/bakooza?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: kang165
      connection-test-query: SELECT NOW() FROM dual
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

my:
  jwt:
    secretKey: PKuqug3YctsBr0Kv0DZeWcGstNRe9Vsc
    refreshKey: miuXdbBehAQwNZ5QGMk2ftRlHM3atoyG